version: '3.8'

services:
  # MongoDB for Notification Service
  hospital-notification-db:
    image: mongo:7-jammy
    container_name: hospital-notification-db-dev
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin_password_123
      MONGO_INITDB_DATABASE: notification_service_db
    volumes:
      - notification_db_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    ports:
      - "27017:27017"
    networks:
      - hospital-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  # RabbitMQ Message Broker
  hospital-rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: hospital-rabbitmq-dev
    environment:
      RABBITMQ_DEFAULT_USER: hospital
      RABBITMQ_DEFAULT_PASS: hospital_mq_123
      RABBITMQ_DEFAULT_VHOST: hospital_vhost
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    ports:
      - "5672:5672"   # AMQP port
      - "15672:15672" # Management UI
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - hospital-network
    restart: unless-stopped

  # Notification Service
  notification-service:
    build:
      context: .
      dockerfile: notification-service/Dockerfile
    image: hospital/notification-service:dev
    container_name: hospital-notification-service-dev
    ports:
      - "3005:3005"
    environment:
      - NODE_ENV=development
      - PORT=3005
      - MONGODB_URI=mongodb://notification_user:notification_password_123@hospital-notification-db:27017/notification_service_db?authSource=admin
      - RABBITMQ_URL=amqp://hospital:hospital_mq_123@hospital-rabbitmq:5672/hospital_vhost
      - NOTIFICATION_QUEUE=notification_queue
      - NOTIFICATION_EXCHANGE=notification_exchange
      - EMAIL_HOST=smtp.gmail.com
      - EMAIL_PORT=587
      - EMAIL_SECURE=false
      - EMAIL_USER=buqcptudw@gmail.com
      - EMAIL_PASSWORD=fakm oirm fwgn cbuf
      - EMAIL_FROM=Hospital Management <noreply@hospital.com>
      - TWILIO_ACCOUNT_SID=your-twilio-account-sid
      - TWILIO_AUTH_TOKEN=your-twilio-auth-token
      - TWILIO_PHONE_NUMBER=+1234567890
      - WEBSOCKET_CORS_ORIGIN=http://localhost:3000
      - SERVICE_NAME=notification-service
      - LOG_LEVEL=info
      - AUTH_SERVICE_URL=http://auth-service:3001
      - PATIENT_SERVICE_URL=http://patient-service:3002
      - APPOINTMENT_SERVICE_URL=http://appointment-service:3003
      - PRESCRIPTION_SERVICE_URL=http://prescription-service:3004
    depends_on:
      hospital-notification-db:
        condition: service_healthy
      hospital-rabbitmq:
        condition: service_healthy
    networks:
      - hospital-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3005/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      # Mount logs for debugging
      - ./notification-service/logs:/app/logs

networks:
  hospital-network:
    driver: bridge

volumes:
  notification_db_data:
  rabbitmq_data:
